/*
     -----------------------------------------------------------

     Code generated by CRA.ModelLayer.ACC - API Code Generator
     http://components.biomamodelling.org/components/acc/help/ 

     Loic Manceau
     loic.manceau@inra.fr
     INRA
     3/29/2018 5:59:40 PM

     -----------------------------------------------------------
*/

using System;
using CRA.AgroManagement;
using CRA.ModelLayer.Strategy;


namespace SiriusQualityPhenology
{
    /// <summary>
    /// SiriusQualityPhenology component model interface   
    /// </summary>
    public interface IStrategySiriusQualityPhenology : IStrategy
    {
        /// <summary>
        /// Calculate method for models
        /// </summary>
        /// <param name=p>PhenologyState Domain class contains the accessors to values</param>
        /// <param name=p1>PhenologyState Domain class contains the accessors to values</param>
        /// <param name=ae>AgroManagement objects of impact parameters</param>
        void Estimate
        ( PhenologyState p, PhenologyState p1, ActEvents ae);
        
        /// <summary>
        /// Test of pre conditions
        /// </summary>
        /// <param name=p>PhenologyState Domain class contains the accessors to values</param>
        /// <param name=p1>PhenologyState Domain class contains the accessors to values</param>
        /// <param name=callID>Preconditions test context</param>
        /// <returns>List of violations</returns>
        string TestPreConditions( PhenologyState p, PhenologyState p1, string callID);
        
        /// <summary>
        /// Test of post-conditions
        /// </summary>
        /// <param name=p>PhenologyState Domain class contains the accessors to values</param>
        /// <param name=p1>PhenologyState Domain class contains the accessors to values</param>
        /// <param name=callID>Postconditions test context</param>
        /// <returns>List of violations</returns>
        string TestPostConditions( PhenologyState p, PhenologyState p1, string callID);
    
        /// <summary>
        /// Set parameters to the default value
        /// </summary>
        void SetParametersDefaultValue();
    }
}
