.. _sectionA:

.. marker_terminology_start

.. _specM_terminology:

Specification description Terminology
-------------------------------------

The keywords "MUST", "MUST NOT", "SHALL", "SHALL NOT", and "MAY" in this document are to be interpreted as described in `RFC 2119 <https://www.ietf.org/rfc/rfc2119.txt>`_ .

The key type of information item "element" and "attribute" have to be interpreted as described in `XML Information Set <https://www.w3.org/TR/2004/REC-xml-infoset-20040204/>`_.

.. _specA_crop2ml_infoset:

**Crop2ML infoset:**
An XML information set containing a hierarchy of information items conforming to the rules described in this document.
In this specification, such infosets are assumed to be Crop2ML infosets.

.. _specA_crop2ml_model:

**Crop2ML model:**
A discrete-time model represented by a hierarchy of one or more Crop2ML infosets, according to the rules described in this document.
In this specification, the topmost Crop2ML infoset in a hierarchy is referred to as the top-level Crop2ML infoset.

.. marker_terminology_end
.. marker_crop2ml_information_sets_start

.. _specM_crop2ml_information_sets:

